version: '3.1'
services:
  app:
    container_name: egen_solutions_ecommerce_app_service
    image: springboot-postgresql
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "3515:3515"
    environment:
      - POSTGRES_PASSWORD=egen_solutions
      - POSTGRES_USER=egen_admin
      - POSTGRES_DB=egendb